// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!A collection of known record types.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "$type")]
pub enum KnownRecord {
    #[serde(rename = "com.macroblog.blog.post")]
    ComMacroblogBlogPost(Box<crate::com::macroblog::blog::post::Record>),
}
impl From<crate::com::macroblog::blog::post::Record> for KnownRecord {
    fn from(record: crate::com::macroblog::blog::post::Record) -> Self {
        KnownRecord::ComMacroblogBlogPost(Box::new(record))
    }
}
impl From<crate::com::macroblog::blog::post::RecordData> for KnownRecord {
    fn from(record_data: crate::com::macroblog::blog::post::RecordData) -> Self {
        KnownRecord::ComMacroblogBlogPost(Box::new(record_data.into()))
    }
}
